# Part One

In [9]:
import numpy as np

In [47]:
a = np.array(list('123'))
b = np.array(list('456'))
c = np.vstack((a,b))
c

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [85]:
foo = np.array([])
print(foo)
bar = np.array([1, 2, 3])
print(bar)
qux = np.concatenate((foo, bar))
print(qux)
baz = np.array([4, 5, 6])
np.concatenate((qux, baz))
np.concatenate((qux, baz[0:4]))

[]
[1 2 3]
[1. 2. 3.]


array([1., 2., 3., 4., 5., 6.])

In [146]:
def get_neighbors(grid, cell_coord):
    i, j = cell_coord
    r, c = grid.shape
    wr, wc = (3, 3) # Sliding window shape
    neighbors = np.array([])
    
    is_at_upper_edge = max(i - 1, 0) == 0 and i != 1
    is_at_lower_edge = min(i + 1, r - 1) == r - 1 and i != r - 2
    is_at_left_edge = max(j - 1, 0) == 0 and j != 1
    is_at_right_edge = min(j + 1, c) == c and j != c - 1

    if not is_at_upper_edge:
        #print("Is not at upper edge")
        temp = grid[i - 1, max(j - 1, 0):min(j + 2, c)]
        neighbors = np.concatenate((neighbors, temp))

    if not is_at_left_edge:
        #print("Is not at left edge")
        temp = grid[i, j - 1:j]
        neighbors = np.concatenate((neighbors, temp))

    if not is_at_right_edge:
        #print("Is not at right edge")
        temp = grid[i, j + 1:j + 2]
        neighbors = np.concatenate((neighbors, temp))

    if not is_at_lower_edge:
        #print("Is not at lower edge")
        temp = grid[i + 1, max(j - 1, 0):min(j + 2, c)]
        neighbors = np.concatenate((neighbors, temp))

    return neighbors

def is_accessible(neighbors):
    encoding = np.where(neighbors == '@', 1, 0)
    paper_roll_count = sum(encoding)
    return paper_roll_count < 4

In [134]:
with open('input.txt', 'r') as file:
    grid = np.array(list(file.readline().strip()))

    while True:
        line = file.readline()

        if not line:
            break

        row = np.array(list(line.strip()))
        grid = np.vstack((grid, row))

neighbors = get_neighbors(grid, (1,1))
print(neighbors)
is_accessible(neighbors)

['.' '@' '@' '.' '@' '@' '@' '.']


False

## Solution

In [148]:

with open('input.txt', 'r') as file:
    grid = np.array(list(file.readline().strip()))

    while True:
        line = file.readline()

        if not line:
            break

        row = np.array(list(line.strip()))
        grid = np.vstack((grid, row))

# Solution inspired by: https://stackoverflow.com/questions/72092204/how-would-i-check-if-each-cell-of-an-array-has-neighbors-of-a-specified-value-qu
r, c = grid.shape
counter = 0

for i in range(0, r):
    for j in range(0, c):
        entry = grid[i,j]
        
        if entry != '@':
            continue

        neighbors = get_neighbors(grid, (i,j))
        if is_accessible(neighbors):
            counter += 1
        
f'The answer is {counter}!'

'The answer is 1540!'

# Part Two